import { GoogleSpreadsheet } from "google-spreadsheet"
import { JWT } from 'google-auth-library';
import 'dotenv/config';


export default async (docID, sheetID) => {
  // console.log(process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL)
  // console.log(process.env.GOOGLE_PRIVATE_KEY)
  const result = []

  const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,

    // 私鑰必須將換行符號替換為真正的換行符號
    key: process.env.GOOGLE_PRIVATE_KEY.split(String.raw`\n`).join('\n'),
    scopes: ['https://www.googleapis.com/auth/spreadsheets'],
  })

  const doc = new GoogleSpreadsheet(docID, serviceAccountAuth)

  await doc.loadInfo()
  console.log(doc.title)

  const sheet = doc.sheetsById[sheetID]
  // return sheet
  const rows = await sheet.getRows()
  for (const row of rows) {
    result.push(row._rawData)
  }
  return result
}