import { GoogleSpreadsheet } from 'google-spreadsheet'
import { JWT } from 'google-auth-library'
import 'dotenv/config'
// import fs from 'node:fs'

// import { superStringify } from '../utils/superStringify.js'

export default async (docID, sheetID) => {
    try {
        // const result = []

        const serviceAccountAuth = new JWT({
            // env var values here are copied from service account credentials generated by google
            // see "Authentication" section in docs for more info
            email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,

            // 私鑰必須將\n替換為真正的換行符號
            key: process.env.GOOGLE_PRIVATE_KEY.split(String.raw`\n`).join('\n'),
            scopes: ['https://www.googleapis.com/auth/spreadsheets']
        })

        const doc = new GoogleSpreadsheet(docID, serviceAccountAuth)

        await doc.loadInfo()
        console.log(doc.title)

        const sheet = doc.sheetsById[sheetID]
        // console.log(sheet)
        // const json = superStringify(sheet, 4)
        // fs.writeFileSync('./dump/sheet.json', json)
        // return sheet
        const rows = await sheet.getRows()
        console.log(rows[1]._rawData)
        console.log(rows[2]._rawData)
        // const json = superStringify(rows, 4)
        // fs.writeFileSync('./dump/sheet.json', json)
        // for (const row of rows) {
        //     result.push(row._rawData)
        // }
        // return result
    } catch (error) {
        console.log(error)
    }
}
